defmodule FleetTracking.Repo.Migrations.AddDriversAndLinkVehicles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vehicles) do
      add :driver_id, :uuid
    end

    create table(:drivers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vehicles) do
      modify :driver_id,
             references(:drivers,
               column: :id,
               name: "vehicles_driver_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:drivers) do
      add :full_name, :text, null: false
      add :phone_number, :text
      add :license_number, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:drivers) do
      remove :updated_at
      remove :inserted_at
      remove :license_number
      remove :phone_number
      remove :full_name
    end

    drop constraint(:vehicles, "vehicles_driver_id_fkey")

    alter table(:vehicles) do
      modify :driver_id, :uuid
    end

    drop table(:drivers)

    alter table(:vehicles) do
      remove :driver_id
    end
  end
end
