defmodule FleetTracking.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vehicles) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :gps_id, :text, null: false
    end
  end

  def down do
    alter table(:vehicles) do
      remove :gps_id
      modify :id, :uuid, default: nil
    end
  end
end
