defmodule FleetTracking.Repo.Migrations.AddLocationLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:location_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :latitude, :float, null: false
      add :longitude, :float, null: false
      add :speed, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vehicle_id,
          references(:vehicles,
            column: :id,
            name: "location_logs_vehicle_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:location_logs, "location_logs_vehicle_id_fkey")

    drop table(:location_logs)
  end
end
